// ─── Prompt 5 — CRM Core: Kanban + Splits Editor + Tasks ───

// ─── Kanban Types ──────────────────────────────────────────

export interface KanbanCard {
  id: string;
  title: string;
  artists: string[];
  releaseDate: string;
  stage: string;
  progress: number; // 0-5 steps completed
  authorizationPending: string; // e.g. "2/3"
  daysInStage: number;
  assignee?: string;
  urgent: boolean;
}

export type KanbanColumn = {
  stage: string;
  label: string;
  cards: KanbanCard[];
};

// ─── Kanban Logic ───────────────────────────────────────────

export const KANBAN_STAGES: Array<{ id: string; label: string }> = [
  { id: "recebido", label: "Recebido" },
  { id: "em_analise", label: "Em Análise" },
  { id: "autorizacao_pendente", label: "Autorização Pendente" },
  { id: "autorizado", label: "Autorizado" },
  { id: "pronto_p_distribuir", label: "Pronto p/ Distribuir" },
  { id: "distribuido", label: "Distribuído" },
  { id: "registrado", label: "Registrado" },
  { id: "concluido", label: "Concluído" },
  { id: "arquivado", label: "Arquivado" },
];

export function organizeKanban(cards: KanbanCard[]): KanbanColumn[] {
  return KANBAN_STAGES.map(stage => ({
    stage: stage.id,
    label: stage.label,
    cards: cards.filter(c => c.stage === stage.id),
  }));
}

export function formatDaysInStage(days: number): string {
  if (days === 0) return "hoje";
  if (days === 1) return "1 dia";
  return `${days} dias`;
}

export function deadlineColor(releaseDate: string): "green" | "amber" | "red" {
  const now = Date.now();
  const release = new Date(releaseDate).getTime();
  const diff = (release - now) / 86400000;
  if (diff > 14) return "green";
  if (diff >= 7) return "amber";
  return "red";
}

// ─── Splits Editor Logic ────────────────────────────────────

export interface SplitEditorLine {
  id: string;
  name: string;
  holder_type: "artist" | "label";
  role_label: string;
  bps100: number;
  is_override: boolean;
}

export function validateSplitTotal(lines: SplitEditorLine[]): { valid: boolean; total: number; delta: number } {
  const total = lines.reduce((s, l) => s + l.bps100, 0);
  return { valid: total === 10_000, total, delta: 10_000 - total };
}

/** Redistribute the remainder: adds delta to the largest line */
export function redistributeRemainder(lines: SplitEditorLine[]): SplitEditorLine[] {
  const { total, delta } = validateSplitTotal(lines);
  if (delta === 0) return lines;

  const maxIdx = lines.reduce((m, l, i) => (l.bps100 > lines[m]!.bps100 ? i : m), 0);
  const result = [...lines];
  result[maxIdx] = { ...result[maxIdx]!, bps100: result[maxIdx]!.bps100 + delta, is_override: true };
  return result;
}

// ─── Task Types ─────────────────────────────────────────────

export type TaskStatus = "aberta" | "em_andamento" | "concluida" | "bloqueada";
export type TaskPriority = "alta" | "media" | "baixa";

export interface Task {
  id: string;
  title: string;
  kind: string;
  status: TaskStatus;
  priority: TaskPriority;
  assignee?: string;
  dueAt?: string;
  completedAt?: string;
  autoGenerated: boolean;
}

export function taskStatusLabel(status: TaskStatus): string {
  return { aberta: "Aberta", em_andamento: "Em Andamento", concluida: "Concluída", bloqueada: "Bloqueada" }[status];
}

export function taskPriorityColor(priority: TaskPriority): "red" | "amber" | "gray" {
  const colors: Record<TaskPriority, "red" | "amber" | "gray"> = { alta: "red", media: "amber", baixa: "gray" };
  return colors[priority];
}

// ─── Dashboard Calculations ─────────────────────────────────

export interface PipelineStats {
  total: number;
  byStage: Record<string, number>;
  avgDaysInStage: Record<string, number>;
}

export function computePipelineStats(rows: Array<{ stage: string; total: number; dias_medio: number }>): PipelineStats {
  const stats: PipelineStats = { total: 0, byStage: {}, avgDaysInStage: {} };
  for (const r of rows) {
    stats.total += r.total;
    stats.byStage[r.stage] = (stats.byStage[r.stage] ?? 0) + r.total;
    stats.avgDaysInStage[r.stage] = Math.round(r.dias_medio * 10) / 10;
  }
  return stats;
}
